<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>PIT.BoletasTransacciones</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-PIT.Boletas.Worker-65c7e2b6-d8b7-40e0-9e46-4bc31e672fd0</UserSecretsId>
    <TesseractPackageVersion>5.2.0</TesseractPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.11" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Serilog.Sinks.EventLog" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PIT.Boletas.Application\PIT.Boletas.Application.csproj" />
    <ProjectReference Include="..\PIT.Boletas.Infrastructure\PIT.Boletas.Infrastructure.csproj" />
    <ProjectReference Include="..\PIT.Boletas.Domain\PIT.Boletas.Domain.csproj" />
    <ProjectReference Include="..\PIT.Boletas.Observability\PIT.Boletas.Observability.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ocr\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <Target Name="CopyTesseractNativeLibraries" AfterTargets="Publish">
    <MakeDir Directories="$(PublishDir)x64;$(PublishDir)x86" />
      <Copy SourceFiles="$(NuGetPackageRoot)tesseract\$(TesseractPackageVersion)\x64\leptonica-1.82.0.dll;$(NuGetPackageRoot)tesseract\$(TesseractPackageVersion)\x64\tesseract50.dll"
        DestinationFiles="$(PublishDir)x64\leptonica-1.82.0.dll;$(PublishDir)x64\tesseract50.dll"
        SkipUnchangedFiles="true" />
      <Copy SourceFiles="$(NuGetPackageRoot)tesseract\$(TesseractPackageVersion)\x86\leptonica-1.82.0.dll;$(NuGetPackageRoot)tesseract\$(TesseractPackageVersion)\x86\tesseract50.dll"
        DestinationFiles="$(PublishDir)x86\leptonica-1.82.0.dll;$(PublishDir)x86\tesseract50.dll"
        SkipUnchangedFiles="true" />
  </Target>
</Project>
