<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PIT.Boletas.Infrastructure\PIT.Boletas.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\PIT.Boletas.Application\PIT.Boletas.Application.csproj" />
  </ItemGroup>
</Project>
